name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env: 
      COMMIT_HASH: $(git rev-parse --short HEAD)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag test-deploy:$COMMIT_HASH

      - name: Run tests
        run: docker run -i test-deploy:$COMMIT_HASH pytest
